name: deploy-book

# Updates on push to main or when triggered manually
on:
  push:
    branches:
    - main
    - dev_amy
  workflow_dispatch:

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install python and dependencies
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install -r binder/requirements.txt

    - name: Build the book
      run: |
        jb build .

    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html