name: deploy-book

# Updates on push to main or when triggered manually
on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Setup Miniconda with python 3.10 and dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: 'latest'
          python-version: 3.10
          environment-file: binder/environment.yml
          activate-environment: qe-mini-example

    - name: Build the book
      run: |
        jb build .

    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html